Working on latestset regexp

diff --git a/backup b/backup
--- a/backup
+++ b/backup
@@ -1,8 +1,79 @@
 # TODO: Need to script a way to find the olddate
 # TODO: Need to script decrypting of the catalogue file
-# TODO: Need to be able to allow monthly to be first weekly and weekly to be first daily
 # TODO: Need to find a way to address the names of the different file labels
 # TODO: Need to find a way to address the storage directories of different levels
+
+daysbetween() {
+  if [[ $# -ne 2 ]]; then
+    echo "Usage: daysbetween <date1> <date2> (date formatted as YYYY-MM-DD)" >&2
+    exit 1
+  fi
+  
+  date1=$1
+  date2=$2
+  
+  if date --version &> /dev/null ; then
+    # This seems like GNU date
+    seconds1=$(date --date="${date1}" +%s) || \
+      { echo "Could not convert date: $date1" >&2 ; exit 1; }
+    seconds2=$(date --date="${date2}" +%s) || \
+      { echo "Could not convert date: $date2" >&2 ; exit 1; }
+  else
+    # Otherwise BSD date
+    seconds1=$(date -j -f "%Y-%m-%d" "${date1}" "+%s") || \
+      { echo "Could not convert date: $date1" >&2 ; exit 1; }
+    seconds2=$(date -j -f "%Y-%m-%d" "${date2}" "+%s") || \
+      { echo "Could not convert date: $date2" >&2 ; exit 1; }
+  fi
+
+  echo $(( (seconds2 - seconds1)/86400 ))	
+}
+
+# Do a monthly if the most recent monthly is more than two months old
+# Do a weekly if the most recent weekly or monthly is more than a week old
+# Do a daily if there's no daily, weekly or monthly from today
+# Exit if there's already a daily, weekly or monthly of this date
+
+latestset() {
+  if [[ $# -ne 1 ]]; then
+    echo "Usage: latestset <directory> <basename>" >&2
+    exit 1
+  fi
+  
+  directory=$1
+  basename=$2
+  
+  # ls "${basename}"'-[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]{,-[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]}{-cat.1,.[0-9]{,[0-9],[0-9][0-9]}}.dar{,.gpg}'
+
+  # This complex regexp pipe is to filter out one- or two-date dar-files,
+  # -cat or not, encrypted or not
+  # Then, cut away all endings, sort and show only one line per set
+  # Finally, show only the date of the most recent set
+  ls "${directory}/" | \
+    grep "^${basename}"'-[[:digit:]]\{4\}-[[:digit:]]\{2\}-[[:digit:]]\{2\}\(\|-[[:digit:]]\{4\}-[[:digit:]]\{2\}-[[:digit:]]\{2\}\)\(-cat\.1\|\.[[:digit:]]*\)\.dar\(\|\.gpg\)$' | \
+    sed 's:\-cat\.[[:digit:]]\.dar\(\.gpg\)*$::' | \
+    sed 's:\.[[:digit:]]*\.dar\(\.gpg\)*$::' | \
+    sort | uniq | \
+    tail -1 | sed 's:.*\([[:digit:]]\{4\}-[[:digit:]]\{2\}-[[:digit:]]\{2\}\)$:\1:'  
+}
+
+# BACKUPSETS=`ls "${STORAGEDIR}/"{monthly,weekly,daily}/ | \
+#   sed 's:\-cat\.1\.dar\(\.gpg\)*$::' | \
+#   sed 's:\.[0-9]*\.dar\(\.gpg\)*$::' | \
+#   sed 's:\.vol[0-9]*+[0-9]*\.par2$::' | \
+#   sed 's:\.par2$::' | \
+#   sort | uniq`
+
+# for BACKUPSET in $BACKUPSETS; do
+#   echo "$BACKUPSET:" `du -hc "${STORAGEDIR}/${BACKUPSET}"*.[dg][ap][rg] | tail -1 | cut -f 1` "(.dar)" \
+# `du -hc "${STORAGEDIR}/${BACKUPSET}"*.par2 | tail -1 | cut -f 1` "(.par2)" 
+# done
+
+  # if there's a cat, use that
+  #  decrypt if decrypted is not available
+  # else use the archives
+  #  decrypt if decrypted is not available
+
 OLDDATE=2009-07-14
 
 # Do a regular daily
